project:
  type: website

website:
  title: "Macroexpand 2025"
  site-url: "https://scicloj.github.io/macroexpand-2025"
  open-graph: true
  navbar:
    search: true
    right:
    - {href: index.qmd, text: Home}
