project:
  type: website

format:
  html:
    theme: cosmo
  
website:
  title: "Macroexpand 2025"
  description: "Clojure online conferences by Scicloj"
  site-url: "https://scicloj.github.io/macroexpand-2025"
  open-graph: true
  image: "images/sci-cloj-logo-transparent.png"
  navbar:
    search: true
    right:
    - {href: index.qmd, text: Home}
    - {href: speakers.qmd, text: Speakers}
    - {href: macroexpand-noj.qmd, text: "Macroexpand-Noj"}
    - {href: macroexpand-deep.qmd, text: "Macroexpand-Deep"}
